<a href="https://colab.research.google.com/github/sudarshan-kumar-m/pregnant-women-health/blob/main/database_with_2_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
df = pd.read_csv("dataset.csv")
df

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0      25         130           80  15.0      98.0         86  high risk
1      35         140           90  13.0      98.0         70  high risk
2      29          90           70   8.0     100.0         80  high risk
3      30         140           85   7.0      98.0         70  high risk
4      35         120           60   6.1      98.0         76   low risk
...   ...         ...          ...   ...       ...        ...        ...
1009   22         120           60  15.0      98.0         80  high risk
1010   55         120           90  18.0      98.0         60  high risk
1011   35          85           60  19.0      98.0         86  high risk
1012   43         120           90  18.0      98.0         70  high risk
1013   32         120           65   6.0     101.0         76   mid risk

[1014 rows x 7 columns]

In [ ]:
data=['Age','SystolicBP','DiastolicBP','BS','BodyTemp','HeartRate']
x=df[data]
target=['RiskLevel']
y=df[target]

In [ ]:
x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.2)

In [ ]:
len(x_train)

811

In [ ]:
len(x_test)

203

In [ ]:
clf=DecisionTreeClassifier()

In [ ]:
clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
x_train

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate
259    21         120           80   6.9      98.0         76
1006   17          85           60   6.3     102.0         86
958    37         120           90  11.0      98.0         88
611    23         120           90   7.5      98.0         60
946    13          90           65   7.5     101.0         80
...   ...         ...          ...   ...       ...        ...
584    32         140           90  18.0      98.0         88
443    32         120           90   6.8      98.0         70
27     22         100           65   7.2      98.0         70
45     32         120           90   7.5      98.0         70
171    12          90           60   7.9     102.0         66

[811 rows x 6 columns]

In [ ]:
clf.predict(x_test)

array(['mid risk', 'mid risk', 'mid risk', 'low risk', 'high risk',
       'mid risk', 'mid risk', 'low risk', 'high risk', 'low risk',
       'low risk', 'low risk', 'low risk', 'high risk', 'low risk',
       'high risk', 'high risk', 'high risk', 'high risk', 'mid risk',
       'low risk', 'mid risk', 'high risk', 'mid risk', 'mid risk',
       'mid risk', 'low risk', 'mid risk', 'mid risk', 'low risk',
       'high risk', 'low risk', 'high risk', 'mid risk', 'high risk',
       'low risk', 'low risk', 'mid risk', 'mid risk', 'low risk',
       'high risk', 'mid risk', 'high risk', 'mid risk', 'mid risk',
       'low risk', 'high risk', 'low risk', 'low risk', 'mid risk',
       'low risk', 'mid risk', 'mid risk', 'mid risk', 'low risk',
       'high risk', 'mid risk', 'mid risk', 'low risk', 'low risk',
       'high risk', 'low risk', 'low risk', 'mid risk', 'low risk',
       'mid risk', 'low risk', 'mid risk', 'low risk', 'mid risk',
       'low risk', 'high risk', 'low risk', 'l

In [ ]:
y_test

RiskLevel
864   mid risk
742   mid risk
820   mid risk
289   low risk
236  high risk
..         ...
570   mid risk
793   mid risk
764   mid risk
237  high risk
753   mid risk

[203 rows x 1 columns]

In [ ]:
clf.score(x_train,y_train)

0.9247842170160296

In [ ]:
y_pred =  clf.predict(x_test)

In [ ]:
y_pred

array(['mid risk', 'mid risk', 'mid risk', 'low risk', 'high risk',
       'mid risk', 'mid risk', 'low risk', 'high risk', 'low risk',
       'low risk', 'low risk', 'low risk', 'high risk', 'low risk',
       'high risk', 'high risk', 'high risk', 'high risk', 'mid risk',
       'low risk', 'mid risk', 'high risk', 'mid risk', 'mid risk',
       'mid risk', 'low risk', 'mid risk', 'mid risk', 'low risk',
       'high risk', 'low risk', 'high risk', 'mid risk', 'high risk',
       'low risk', 'low risk', 'mid risk', 'mid risk', 'low risk',
       'high risk', 'mid risk', 'high risk', 'mid risk', 'mid risk',
       'low risk', 'high risk', 'low risk', 'low risk', 'mid risk',
       'low risk', 'mid risk', 'mid risk', 'mid risk', 'low risk',
       'high risk', 'mid risk', 'mid risk', 'low risk', 'low risk',
       'high risk', 'low risk', 'low risk', 'mid risk', 'low risk',
       'mid risk', 'low risk', 'mid risk', 'low risk', 'mid risk',
       'low risk', 'high risk', 'low risk', 'l

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[45  1  7]
 [ 1 75 12]
 [ 3  7 52]]


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

   high risk       0.92      0.85      0.88        53
    low risk       0.90      0.85      0.88        88
    mid risk       0.73      0.84      0.78        62

    accuracy                           0.85       203
   macro avg       0.85      0.85      0.85       203
weighted avg       0.86      0.85      0.85       203



In [ ]:
from sklearn.metrics import plot_roc_curve

# K near neighbour

In [ ]:
import matplotlib.pyplot as plt


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [ ]:
y_pred=classifier.predict(x_test)

In [ ]:
y_pred

array(['mid risk', 'mid risk', 'mid risk', 'mid risk', 'high risk',
       'mid risk', 'low risk', 'mid risk', 'mid risk', 'low risk',
       'low risk', 'low risk', 'low risk', 'high risk', 'low risk',
       'high risk', 'mid risk', 'high risk', 'high risk', 'mid risk',
       'mid risk', 'mid risk', 'high risk', 'mid risk', 'low risk',
       'mid risk', 'mid risk', 'mid risk', 'mid risk', 'low risk',
       'high risk', 'mid risk', 'high risk', 'mid risk', 'high risk',
       'low risk', 'low risk', 'mid risk', 'mid risk', 'low risk',
       'high risk', 'low risk', 'high risk', 'mid risk', 'low risk',
       'mid risk', 'high risk', 'low risk', 'low risk', 'low risk',
       'high risk', 'mid risk', 'low risk', 'mid risk', 'low risk',
       'high risk', 'high risk', 'low risk', 'low risk', 'low risk',
       'high risk', 'low risk', 'low risk', 'mid risk', 'high risk',
       'mid risk', 'mid risk', 'mid risk', 'mid risk', 'mid risk',
       'low risk', 'high risk', 'low risk', '

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[39  5  9]
 [ 4 63 21]
 [ 2 16 44]]


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

   high risk       0.87      0.74      0.80        53
    low risk       0.75      0.72      0.73        88
    mid risk       0.59      0.71      0.65        62

    accuracy                           0.72       203
   macro avg       0.74      0.72      0.73       203
weighted avg       0.73      0.72      0.72       203



In [ ]:
classifier.score(x_train,y_train)

0.781750924784217